# Global
timezone: Australia/Sydney
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://teamred.rocks" # the base hostname & protocol for your site, e.g. http://example.com
future: true

# Site Metadata
title: TeamRed Rocks
author: curtis
email: "&#x63;&#x75;&#x72;&#x74;&#x69;&#x73;&#x40;&#x63;&#x75;&#x72;&#x74;&#x69;&#x73;&#x6D;&#x2E;&#x6D;&#x65;"
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: CurtisMillar
github_username:  studley13
disqus:
  shortname: teamred-rocks
google_analytics: UA-51914975-2

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
      author: curtis
  - scope:
      path: ""
      type: posts
    values:
      layout: default

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
