# Global
timezone: Australia/Sydney
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xurtis.pw" # the base hostname & protocol for your site, e.g. http://example.com
future: true
show_downloads: false
cayman-blog:
  date_format: "%-d %b %Y"

# Site Metadata
title: "Curtis Millar"
author: "Curtis Millar"
email: "&#x63;&#x75;&#x72;&#x74;&#x69;&#x73;&#x40;&#x78;&#x75;&#x72;&#x74;&#x69;&#x73;&#x2E;&#x70;&#x77;"
description: >
  Teacher and student with the faculty of Computer Science and Engineering
  at UNSW Sydney.
twitter:
  username: CurtisMillar
github_username:  xurtis
disqus:
  shortname: xurtis-pw
google_analytics: UA-51914975-2

collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
