# Redirection specifications

# Format:
# ["path"]
# title = "Page / redirect title"
# url = "https://example.com/path/to/redirect"
# index = false

# Special root is the root directory redirect
["."]
title = "xurt.is"
url = "https://xurt.is"
# Display this link in the index
index = false

[lca2020]
title = "Anatomy of a run-time"
url = "https://docs.google.com/presentation/d/1W5xIwWg8YAUbJ_8Y_qhFh7cIchE5vwRvgUZuRiJqLOY/view"
index = true

[nsa-app]
title = "Original substitution cipher guessing app"
url = "https://nsa-app.xurt.is/"
index = true

[nsa-crypto]
title = "Updated substitution cipher guessing app"
url = "https://nsa-crypto.xurt.is/"
index = true

[lca2021]
title = "Slides for the import presentation at LCA 2021"
url = "https://github.com/xurtis/import/blob/c7d90ab385c887ab281df5fc0e8a59c5e762f832/slides/slides.sh"
index = true

[import-slides]
title = "Slides for the import presentation"
url = "https://github.com/xurtis/import/blob/master/slides/slides.sh"
index = true
