# Redirection specifications

# Format:
# ["path"]
# title = "Page / redirect title"
# url = "https://example.com/path/to/redirect"
# index = false

# Special root is the root directory redirect
["."]
title = "xurt.is"
url = "https://xurt.is"
# Display this link in the index
index = false

[lca2020]
title = "Anatomy of a run-time"
url = "https://docs.google.com/presentation/d/1W5xIwWg8YAUbJ_8Y_qhFh7cIchE5vwRvgUZuRiJqLOY/view"
index = true

[nsa-app]
title = "Original substitution cipher guessing app"
url = "https://nsa-app.xurt.is/"
index = true

[nsa-crypto]
title = "Updated substitution cipher guessing app"
url = "https://nsa-crypto.xurt.is/"
index = true

[lca2021]
title = "Slides for the import presentation at LCA 2021"
url = "https://github.com/xurtis/import/blob/d38d403c7ef12b87f40975b2d337b0281a083809/slides/slides.sh"
index = true

[import-slides]
title = "Slides for the import presentation"
url = "https://github.com/xurtis/import/blob/master/slides/slides.sh"
index = true

[mcs-doodle-febuary-2021]
title = "MCS Meeting time selection doodle (February 2021)"
url = "https://doodle.com/poll/76x5dq9yum36z3w6?utm_source=poll&utm_medium=link"
index = false

["test"]
title="Test encrypted URL"
url="https://xurtis.pw/decrypt.html?name=test&password_salt=I3wnfXpPmjNFWerhWJ4B9g%3D%3D&ciphertext=o73xIq9zA2asvHUS8NFga9Zm1ASRxuboXbuRagBHNOA15gI8G4%2FaqRp6vA%3D%3D&counter=75GY1UDK8u5gcozKR4RP4w%3D%3D&digest=BCSXTGhTApBFjI1YZ04mN%2FZavBJwV5V9ezrL0kwgj5M%3D"
index=false
