name: Generate redirect pages
on:
  push:
    branches:
      - main
jobs:
  generate-redirects:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install python dependencies
        run: python3 -m pip install toml
      - name: Generate link files
        run: python3 gen-links.py
      - name: Save and commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "Update link files"

          git push

